# Generated by Django 5.1.3 on 2024-12-08 19:51

from django.db import migrations, models
from django.utils import timezone

def copy_timestamp_to_created_at(apps, schema_editor):
    Click = apps.get_model('tracker', 'Click')
    for click in Click.objects.all():
        click.created_at = click.timestamp
        click.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_click_created_at'),
    ]

    operations = [
        migrations.RunPython(copy_timestamp_to_created_at),
    ]
