# Generated by Django 5.1.3 on 2024-12-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_auto_20241208_2351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="click",
            name="created_at",
        ),
    ]
